app/non_tech/forms.py
# type: ignore
from flask import current_app
from flask_wtf import FlaskForm 
from wtforms import StringField, PasswordField, SubmitField, BooleanField, EmailField, SelectField, TextAreaField, IntegerField
from wtforms.validators import InputRequired, length, Email, EqualTo, DataRequired, ValidationError
from ..models import User, Ticket, IT, UserTicket



class NewTicketForm(FlaskForm):
    # ticket_number = Ticket.query.filter_by(ticket_id).last()
    # if ticket_number is None or ticket_number == 0:
    #     ticket_number = 1
    # else:
    #     ticket_number += 1

    # id = IntegerField("Ticket ID", validators=[InputRequired, length(1, 6)], default=ticket_number, render_kw={'readonly': True})

    
    ticket_branch = SelectField("Ticket Branch", choices=["", "Head Quarter", "Heliopolis", "Nasr City", "New Cairo", "6th October"], validate_choice=True, validators=[InputRequired()])   
  
    ticket_type = SelectField("Ticket Type", choices=["","Request", "Complain"], validators=[InputRequired()],  validate_choice=True)    
    category = SelectField("Category", choices=["", "Mobile network connection", "PC network connection",\
         "PC hardware", "PC software", "Printer", "Mouse", "Keboard"],\
         validators=[InputRequired()],  validate_choice=True)
    title = StringField("Title", validators=[InputRequired(), length(max=50)])
    ticket_details = TextAreaField("Details", validators=[InputRequired()])
    submit = SubmitField('Submit')



    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.generate_ticket_number()

    def generate_ticket_number(self):
        with current_app.app_context():
            latest_ticket = Ticket.query.order_by(Ticket.ticket_id.desc()).first()
            if latest_ticket:
                self.ticket_number = latest_ticket.ticket_id + 1
            else:
                self.ticket_number = 1

    @property
    def ticket_number(self):
        return IntegerField("Ticket ID", validators=[InputRequired, length(1, 6)], render_kw={'readonly': True})    

    def validate_ticket_type(self, ticket_type):
        if ticket_type == "":
            raise ValidationError("Ticket Type can't be empty. You have to choose a type.")
        
    def validate_ticket_branch(self, ticket_branch):
        if ticket_branch == "":
            raise ValidationError("Ticket Branch can't be empty. You have to choose the branch.")
        

    def validate_ticket_category(self, category):
        if category == "":
            raise ValidationError("Ticket Title can't be empty.")

app/non_tech/__init__.py
# type: ignore

from flask import Blueprint

non_tech = Blueprint("non_tech", __name__, template_folder="templates")

from . import forms, views, errors

app/non_tech/views.py
# type: ignore
from flask import render_template, redirect, request, url_for, flash
from . import non_tech
from flask_login import login_user, logout_user, login_required, current_user
from ..models import Ticket
from .forms import NewTicketForm


@non_tech.route("/new-ticket", methods=["GET", "POST"])
def non_tech_new_ticket():
    form=NewTicketForm()

    # Generate ticket number
    with current_app.app_context():
        latest_ticket = Ticket.query.order_by(Ticket.ticket_id.desc()).first()
        if latest_ticket:
            form.ticket_number.data = latest_ticket.ticket_id + 1
        else:
            form.ticket_number.data = 1


    # Get current UTC time
    current_datetime = datetime.now(timezone.utc)

    if form.validate_on_submit():
        try:
            # ticket_number
            # form.generate_ticket_number()
            ticket_number = form.ticket_number.data
            ticket_branch = form.ticket_branch.data
            ticket_type = form.ticket_type.data
            category = form.category.data
            title = form.title.data
            ticket_details = form.ticket_details.data
            
            # password = form.password.data
            ticket = Ticket(
                ticket_id=ticket_number,
                ticket_branch=ticket_branch,
                ticket_type=ticket_type,
                ticket_category=category,
                ticket_title=title,
                ticket_details=ticket_details,
                submission_datetime=current_datetime
                )
            
            
            db.session.add(ticket)
            db.session.commit()
            
            flash(f'Ticket created successfully. Your ticket number is: {form.ticket_number.data}.', 'success')
            return redirect(url_for('tech.tech_dashboard'))
        except Exception as e:
            db.session.rollback()
            error_message = str(e)
            return render_template('register.html', form=form, error=error_message)
    
    return render_template("non-tech_add_ticket.html", title="ITicket - New Ticket", form=form)

@non_tech.route("/all-tickets")
def all_ticket():
    tickets = Ticket.query.all()
    return render_template("non-tech_all-tickets.html", title="ITicket - User Dashboard", tickets=tickets)

app/non_tech/templates/non-tech_add_ticket.html
{% extends "non-tech_layer.html" %}


{% block content %}

<div id="new-container">

    <form method="POST" action="">
        {{ form.hidden_tag() }}
        
        <div class="form-group">
            <div class="row">
                <div class="col-6">

                    {{ form.ticket_branch.label(class="form-label") }}
                    {% if form.ticket_branch.errors %}
                    {{ form.ticket_branch(class="form-control form-control is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.ticket_branch.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                    {% else %}
                        {{ form.ticket_branch(class="form-control form-control") }}                    
                    {% endif %}

                    <!-- <label for="ticketType" class="form-label">Ticket Type</label>
                    <select class="form-select">
                        <option></option>
                        <option>Request</option>
                        <option>Complain</option>    
                    </select> -->
                    <!-- {{ form.ticket_type.label(class="form-label") }}
                    {% if form.ticket_type.errors %}
                    {{ form.ticket_type(class="form-control form-control is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.ticket_type.errors %}
                            <span>{{ error }}</span>
                        {% endfor %} -->
                    <!-- </div>
                {% else %}
                    {{ form.ticket_type(class="form-control form-control") }}                    
                {% endif %} -->
                </div>

                <div class="col-6">
                    <label for="ticketID" class="form-label">Ticket Number</label>
                    <input type="text" id="ticketID" name="ticket_number" class="form-control" readonly value="{{ form.ticket_number.data }}">
                </div>
                
                <!-- <div class="col-6"> -->
                    <!-- <label for="ticketID" class="form-label">Ticket Number </label>
                    <input type="text" class="form-control" id="ticketID" placeholder="100" readonly> -->
                    <!-- {{ form.ticket_number.label(class="form-label") }}
                    {% if form.ticket_number.errors %}
                    {{ form.ticket_number(class="form-control form-control is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.ticket_number.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                    {% else %}
                        {{ form.ticket_number(class="form-control form-control", readonly=true) }}                    
                    {% endif %}                    

                </div> -->
            </div>

            <div>
                {{ form.ticket_type.label(class="form-label") }}
                {% if form.ticket_type.errors %}
                {{ form.ticket_type(class="form-control form-control is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.ticket_type.errors %}
                        <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% else %}
                    {{ form.ticket_type(class="form-control form-control") }}                    
                {% endif %}


                <!-- <label for="ticket-branch" class="form-label">Ticket Branch</label>
                <select class="form-select">
                    <option></option>
                    <option>Head Quarter</option>
                    <option>Heliopolis</option>
                    <option>Nasr City (Complain)</option>
                    <option>Water Way (Complain)</option> 
                </select> -->
                <!-- {{ form.ticket_branch.label(class="form-label") }}
                {% if form.ticket_branch.errors %}
                {{ form.ticket_branch(class="form-control form-control is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.ticket_branch.errors %}
                        <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% else %}
                    {{ form.ticket_branch(class="form-control form-control") }}                    
                {% endif %}  -->
            </div>

            <div>
                <!-- <label for="ticketRequest" class="form-label">Ticket Request</label>
                <select class="form-select">
                    <option></option>
                    <option>Mouse</option>
                    <option>Keboard</option>
                    <option>Mobile Network (Complain)</option>
                    <option>PC Network (Complain)</option> 
                </select> -->

                {{ form.category.label(class="form-label") }}
                {% if form.category.errors %}
                {{ form.category(class="form-control form-control is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.category.errors %}
                        <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% else %}
                    {{ form.category(class="form-control form-control") }}                    
                {% endif %} 
            </div>
            <div>
                <!-- <label for="ticket-subject" class="form-label">Ticket Title</label>
                <input type="text" class="form-control" id="ticket-subject" placeholder="Enter a subject for your ticket"> -->

                {{ form.title.label(class="form-label") }}
                {% if form.title.errors %}
                {{ form.title(class="form-control form-control is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.title.errors %}
                        <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% else %}
                    {{ form.title(class="form-control form-control") }}                    
                {% endif %} 

            </div>
            <div>
                <!-- <label for="ticket-details" class="form-label">Ticket Details</label>
                <textarea type="text" class="form-control" id="ticket-details" placeholder="Add more detailes..."></textarea> -->

                {{ form.ticket_details.label(class="form-label") }}
                {% if form.ticket_details.errors %}
                {{ form.ticket_details(class="form-control form-control is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.ticket_details.errors %}
                        <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% else %}
                    {{ form.ticket_details(class="form-control form-control") }}                    
                {% endif %}                

            </div>
        </div>
        <div class="sub-bt">
            <button type="submit" class="btn btn-primary">Submit</button>
        </div>
    </form>

</div>

{% endblock content %}

app/non_tech/templates/non-tech_all-tickets.html
{% extends "non-tech_layer.html" %}


{% block content %}

<div id="non-tech_tickets_table">
    <table class="table table-bordered table-striped ">
        <thead>
            <tr>
                <th scope="col"> Ticket Number </th>
                <th scope="col"> Ticket Branch </th>
                <th scope="col"> Ticket Type </th>
                <th scope="col"> Category </th>
                <th scope="col"> Title </th>
                <th scope="col"> Details </th>
                <th scope="col"> Submition date </th>
                <th scope="col"> Status </th>
                <th scope="col"> Status Date </th>
                <th scope="col"> IT </th>
                <th scope="col"> Comment (optional) </th>
            </tr>
        </thead>

        <tbody>
            {% for ticket in tickets %}
            <tr>
                <td>{{ ticket.ticket_id }}</td>
                <td>{{ ticket.ticket_branch }}</td>
                <td>{{ ticket.ticket_type }}</td>
                <td>{{ ticket.ticket_category }}</td>
                <td>{{ ticket.ticket_title }}</td>
                <td>{{ ticket.ticket_details }}</td>
                <td>{{ ticket.submission_datetime }}</td>
                <td>{{ ticket.ticket_status}}</td>
                <td>Status Date</td>
                <td>Tech User Name</td>
                <td>Comment (optional) </td>
            </tr>
            {% endfor %}
        </tbody>

    </table>
</div>

{% endblock content %}

app/non_tech/templates/non-tech_layer.html
{% extends "base_layer.html" %}



{% block navbar %}

<div class="nav-bar">
    <ul>
        <li> <a class="bi bi-house-door-fill" href="{{ url_for('non_tech.non_tech_new_ticket') }}"> Home </a> </li>
        <li> <a class="bi bi-person-fill" href="#"> Profile </a> </li>
        <li> <a class="bi bi-door-open-fill fixed-bottom" href="{{ url_for('auth.login') }}"> LogOut </a> </li>
    </ul>
</div>

{% endblock navbar %}

{% block tabbar %}

<div id="flash">
    {% for message in get_flashed_messages(with_categories=true) %}
    <div class="alert alert-{{ message[0] }}">
        {{ message[1] }}
    </div>
    {%endfor%}
</div>

<div class="content" id="tabs-bar">
    <nav class="nav nav-tabs">
        <a href="{{ url_for('non_tech.non_tech_new_ticket') }}" class="nav-item nav-link">
            <i class="bi-plus-square"></i> New Ticket
        </a>
        <a href="{{ url_for('non_tech.all_ticket') }}" class="nav-item nav-link">
            <i class="bi-card-list"></i> All Tickets
        </a>
    </nav>
</div>

{% endblock tabbar %}

{% block content %}

{% endblock content %}